/**
 * __ai_context__:
 * This module defines the core, hyper-explicit data structures for the GoodPhoto application.
 * It serves as the single source of truth for the communication between the UI, the local
 * image processor, and the external Vision Language Model (Alibaba Qwen).
 *
 * Types are structured to prevent hallucinations and enforce rigid data contracts.
 */

import type { LlmProviderId } from "./llmProviders";

// ============================================================================
// Stage 1: Aesthetic Manifestation (审美显化)
// ============================================================================

/**
 * Represents the detailed aesthetic criteria that the VLM will use to score images.
 * This is generated by an LLM based on user's vague prompt, or manually adjusted by the user.
 */
export interface AestheticCriteria {
    /**
     * The overarching theme or mood (e.g., "Cinematic Cyberpunk", "Soft Japanese Film").
     */
    theme: string;

    /**
     * 主体对象描述：形态特征、动作/姿态要求。
     * Subject description: form/features, action or posture requirements.
     * e.g., ["人物表情自然放松", "肢体语言舒展", "主体占画面1/3以上"]
     */
    subject: string[];

    /**
     * 背景环境要求：场景设定、空间关系、环境细节。
     * Background environment: scene setting, spatial relationships, environmental details.
     * e.g., ["浅景深虚化背景", "背景无杂乱元素", "具备叙事性场景感"]
     */
    background: string[];

    /**
     * 光线效果要求：光源方向、光影对比、照明氛围。
     * Lighting: light source direction, contrast, atmosphere.
     * e.g., ["侧逆光勾勒轮廓", "光比柔和不过曝", "黄金时段暖光氛围"]
     */
    lighting: string[];

    /**
     * 色调方案：主色调、配色关系、色彩饱和度。
     * Color scheme: primary tone, color relationships, saturation level.
     * e.g., ["低饱和日系色调", "冷暖对比鲜明", "主色为米白与深棕"]
     */
    colorScheme: string[];

    /**
     * 艺术风格：具体流派、技法特点、风格标签。
     * Artistic style: genre, technique characteristics, style tags.
     * e.g., ["胶片颗粒感", "高对比黑白街拍", "Vsco滤镜风格"]
     */
    artisticStyle: string[];

    /**
     * Explicit rules for composition (e.g., "Rule of thirds", "Leading lines", "Symmetrical").
     * 保留构图规则字段以兼容现有打分流程
     */
    compositionRules: string[];

    /**
     * Explicit list of things to AVOID (e.g., "Blurry", "Overexposed", "Messy background").
     */
    negativeConstraints: string[];
}

// ============================================================================
// Stage 2: Local Processed Images (本地预处理)
// ============================================================================

/**
 * Tracks the state of a single user-provided localized photographic image.
 */
export interface ProcessedImage {
    /**
     * Unique identifier (UUID v4 recommended) for referencing across the UI and backend.
     */
    id: string;

    /**
     * The absolute path to the original, high-resolution file on the user's local disk.
     * This is CRITICAL for the final "export" phase, to copy the actual high-res photo.
     */
    originalFilePath: string;

    /**
     * The local filename without full path, useful for display.
     */
    filename: string;

    /**
     * User-defined custom tags (e.g., "#Instagram", "#Print").
     */
    customTags?: string[];

    /**
     * A Base64 Data URL (e.g., "data:image/jpeg;base64,....") representing a uniformly
     * scaled-down version of the image where max(width, height) <= 1024.
     * This is the exact payload sent to the VLM to save bandwidth.
     */
    compressedBase64: string;

    /**
     * Status of this image in the processing/evaluation pipeline.
     */
    status: 'PENDING' | 'COMPRESSING' | 'EVALUATING' | 'DONE' | 'ERROR';
}

// ============================================================================
// Stage 3: Evaluation Output (AI评分与输出)
// ============================================================================

/**
 * A single evaluation record returned by the VLM for a specific image.
 */
export interface ImageEvaluationResult {
    /**
     * Must exactly match the ProcessedImage.id
     */
    imageId: string;

    /**
     * A score out of 100 based on how well the image fits the AestheticCriteria.
     * 100 = Perfect match, 0 = Complete mismatch
     */
    score: number;

    /**
     * A one-line definitive reasoning for the given score.
     */
    reasoning: string;

    /**
     * Whether this image is recommended by the AI to be kept/exported.
     */
    isRecommended: boolean;

    /**
     * Extracted structured OCR information for Commercial POS/Business Card profiles.
     */
    extractedData?: Record<string, string>;
}

// ============================================================================
// Application Global State (应用全局状态)
// ============================================================================

export interface AppState {
    /**
     * The vague, initial user prompt (e.g., "I want some moody street photos").
     */
    userInitialIntent: string;

    /**
     * The expanded, structured criteria generated from the userInitialIntent.
     */
    criteria: AestheticCriteria | null;

    /**
     * The dictionary of all images currently loaded into the app workspace.
     */
    images: Record<string, ProcessedImage>;

    /**
     * The resulting evaluations for each image, keyed by ProcessedImage.id.
     */
    evaluations: Record<string, ImageEvaluationResult>;
}

// [For Future AI]
// 1. Key assumptions made:
//    - Images will be compressed on the main thread or web worker *before* touching the network.
//    - The VLM API will confidently return structured JSON adhering to ImageEvaluationResult.
// 2. Potential edge cases to watch:
//    - Very large EXIF data or color profiles might get stripped during canvas compression; this is acceptable as we only compress for visual evaluation.
//    - `originalFilePath` relies on desktop environments exposing full native paths, which Tauri provides but standard Web APIs do not.
// 3. Dependencies on other modules:
//    - Tauri file system APIs for reading the original file path on drop events.
//    - Local Canvas API for implementing the 1024px clamping mechanism.
export interface ExifData {
    model?: string;
    focalLength?: number;
    fNumber?: number;
    iso?: number;
    exposureTime?: number | string; // 1/200 格式
    dateTimeOriginal?: string;
    width?: number;
    height?: number;
}

export interface FileNode {
    name: string;
    isDirectory: boolean;
    path: string;
    size?: number;
}

export interface ProviderConfig {
    apiKey: string;
    baseUrl: string;
    model: string;
}

export interface AestheticProfile {
    id: string;
    name: string;
    description: string;
    systemPrompt: string;
    evaluationStandard: string;
    isCustom?: boolean;
}

export interface LlmConfig {
    activeProvider: LlmProviderId;
    providers: Record<LlmProviderId | "stability", ProviderConfig>;
}
